joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

joint1_position_controller:
  type: effort_controllers/JointPositionController
  joint: base_link__link_01RIGHT
  pid: {p: 20000.0, i: 1000, d: 5000.0}
joint2_position_controller:
  type: effort_controllers/JointPositionController
  joint: link_1RIGHT__link_2RIGHT
  pid: {p: 10000.0, i: 800, d: 3000.0}
joint3_position_controller:
  type: effort_controllers/JointPositionController
  joint: link_2RIGHT__link_3RIGHT
  pid: {p: 5000.0, i: 500, d: 2000.0}
joint4_position_controller:
  type: effort_controllers/JointPositionController
  joint: link_3RIGHT__link_5RIGHT
  pid: {p: 3000.0, i: 300, d: 1000.0}
joint5_position_controller:
  type: effort_controllers/JointPositionController
  joint: GRIPPER_1_RIGHT
  pid: {p: 100.0, i: 10, d: 50.0}
joint6_position_controller:
  type: effort_controllers/JointPositionController
  joint: GRIPPER_2_RIGHT
  pid: {p: 100.0, i: 10, d: 50.0}
joint7_position_controller:
  type: effort_controllers/JointPositionController
  joint: base_link__link_01LEFT
  pid: {p: 20000.0, i: 1000, d: 5000.0}
joint8_position_controller:
  type: effort_controllers/JointPositionController
  joint: link_1LEFT__link_2LEFT
  pid: {p: 10000.0, i: 800, d: 3000.0}
joint9_position_controller:
  type: effort_controllers/JointPositionController
  joint: link_2LEFT__link_3LEFT
  pid: {p: 5000.0, i: 500, d: 2000.0}
joint10_position_controller:
  type: effort_controllers/JointPositionController
  joint: link_3LEFT__link_5LEFT
  pid: {p: 3000.0, i: 300, d: 1000.0}
joint11_position_controller:
  type: effort_controllers/JointPositionController
  joint: GRIPPER_1_LEFT
  pid: {p: 100.0, i: 10, d: 50.0}
joint12_position_controller:
  type: effort_controllers/JointPositionController
  joint: GRIPPER_2_LEFT
  pid: {p: 100.0, i: 10, d: 50.0}