# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: left_arm
  joint_model_group_pose: l1
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - base_link__link_01LEFT
    - link_1LEFT__link_2LEFT
    - link_2LEFT__link_3LEFT
    - link_3LEFT__link_5LEFT
    - GRIPPER_1_LEFT
    - GRIPPER_2_LEFT
    - base_link__link_01RIGHT
    - link_1RIGHT__link_2RIGHT
    - link_2RIGHT__link_3RIGHT
    - link_3RIGHT__link_5RIGHT
    - GRIPPER_1_RIGHT
    - GRIPPER_2_RIGHT
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: left_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - base_link__link_01LEFT
      - link_1LEFT__link_2LEFT
      - link_2LEFT__link_3LEFT
      - link_3LEFT__link_5LEFT
      - GRIPPER_1_LEFT
      - GRIPPER_2_LEFT
  - name: right_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - base_link__link_01RIGHT
      - link_1RIGHT__link_2RIGHT
      - link_2RIGHT__link_3RIGHT
      - link_3RIGHT__link_5RIGHT
      - GRIPPER_1_RIGHT
      - GRIPPER_2_RIGHT